### ISSUE TITLE
Definir Frontend

### ISSUE THREAD

**Issue by jorge9372** [n-Finit-Dev/Gitducate#3]
Con este link podemos mirar
https://www.toptal.com/next-js/next-js-vs-react

**Comment by jorge9372** [comment]
Here is a suggested suite of technologies & tools for the Gitducate frontend:


# Tecnology - Framework or Library 
 - [ ] React.js
 - [x] Next.js
 - [ ] Vue.js
 - [ ] Angular

# Programming language

- [ ] Typescript
- [ ] JavaScript

# State management

- [ ] Zustand 
- [ ] Redux
- [ ] MobX

# Styling Technology

- [ ] CSS
- [ ] SASS
- [ ] Tailwind CSS
- [ ]  Bootstrap 
- [ ] Chakra UI

# Testing

- [ ] Jest
- [ ] Mocha
- [ ] React Testing Library
- [ ] Vue Testing Librar
- [ ] Cypress

# Package manager

- [ ] npm
- [ ] yarn

**Comment by rpalaciosg** [comment]
## Programming language
- [x] Typescript
- [ ] JavaScript
## State management
 - [x] Zustand -> me gustaria apredner zustand
 - [ ] Redux
 - [ ] MobX
## Styling Technology
 - [ ] CSS
 - [ ] SASS
 - [ ] Tailwind CSS
 - [ ] Bootstrap
 - [x] Chakra UI

##Testing
- [x] Jest
- [ ] Mocha
- [ ] React Testing Library
- [ ] Vue Testing Librar
- [x] Cypress
## Package manager
- [x] npm
- [ ] yarn
- [x] pnpm
